AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TerminateServer

Globals:
  Function:
    Timeout: 5

Resources:
  TerminateServer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: terminate-server/
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Environment:
        Variables:
          PARAM1: VALUE