AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  EmbedManager

Globals:
  Function:
    Timeout: 100

Resources:
  EmbedManager:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: embed-manager/
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Environment:
        Variables:
          DISCORD_TOKEN: NzEzODU3NDM5MjIwMzY3NDMy.XsmNjA.4ySuplYlYEdMww9sEJjwoIE6xKM
          SERVER_TABLE: ServerBoi-Server-List