AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:
  ProvisionServer
  Sample SAM Template for ProvisionServer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  ProvisionServer:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: provision-server/
      Handler: main
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          SERVER_TABLE: ServerBoi-Server-List
          OWNER_TABLE: ServerBoi-Owner-List
          AWS_REGION: us-west-2
          DYNAMO_CONTAINER: serverboi-dynamodb-local
          LOCALSTACK_CONTAINER: serverboi-localstack
          API_URL: https://api.serverboi.io
          CONFIGURATION_BUCKET: serverboi-provision-configuration-bucket
          COMPOSE_BUCKET: serverboi-docker-compose-bucket
          KEY_BUCKET: serverboi-provision-configuration-bucket
          DISCORD_TOKEN: a
