version: '3.8'
services:
  dynamo:
    container_name: serverboi-dynamodb-local
    image: amazon/dynamodb-local
    env_file:
      - ./test-env.txt
    networks:
      - backend
    ports:
      - 8000:8000
    volumes:
      - ./.test-volumes/dynamo:/database/dynamo
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath /database/dynamo'

  localstack:
    image: localstack/localstack
    container_name: serverboi-localstack
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
      - "8055:8080"
    networks:
      - backend
    environment:
      - SERVICES=ec2,sts
      - DEBUG=1
      - DATA_DIR=.test-volumes/localstack
    volumes:
      - "./.test-volumes/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  backend:
    name: serverboi-backend
